#define USE_SERIAL
#define EE_HANDS

#define NO_ACTION_ONESHOT

#undef RGBLED_NUM
#define RGBLED_NUM 12
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_CHRISTMAS_STEP 6
#define RGBLIGHT_EFFECT_CHRISTMAS_INTERVAL 800
#define RGBLIGHT_EFFECT_KNIGHT_LENGTH 6
#define RGBLIGHT_EFFECT_BREATHE_CENTER 1.25 // 1-2.7
#define RGBLIGHT_EFFECT_BREATHE_MAX 255   // 0-255
#define RGBLIGHT_EFFECT_SNAKE_LENGTH 12
#define RGBLIGHT_SLEEP

#define PERMISSIVE_HOLD
#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 1
#undef TAPPING_TERM
#define TAPPING_TERM 175
#define FORCE_NKRO
#undef TAP_HOLD_CAPS_DELAY
#define TAP_HOLD_CAPS_DELAY 0

#undef QMK_ESC_OUTPUT
#undef QMK_ESC_INPUT
#define QMK_ESC_OUTPUT D2
#define QMK_ESC_INPUT F1
