#pragma once

#define USE_SERIAL
#define EE_HANDS

#ifdef RGBLIGHT_ENABLE
	#undef RGBLED_NUM
	#define RGBLED_NUM 12
	#undef RGBLIGHT_EFFECT_CHRISTMAS_STEP
	#define RGBLIGHT_EFFECT_CHRISTMAS_STEP 3
	#undef RGBLIGHT_RAINBOW_SWIRL_RANGE
	#define RGBLIGHT_RAINBOW_SWIRL_RANGE 63
#endif

#ifdef AUDIO_ENABLE
	#define C6_AUDIO
#endif
