BOOTMAGIC_ENABLE = no       			# Virtual DIP switch configuration(+1000)
MOUSEKEY_ENABLE = no        			# Mouse keys(+4700)
EXTRAKEY_ENABLE = yes       			# Audio control and System control(+450)
CONSOLE_ENABLE = no         			# Console for debug(+400)
COMMAND_ENABLE = no         			# Commands for debug and configuration
NKRO_ENABLE = yes           			# N-key Rollover
AUDIO_ENABLE = no           			# Audio output on port C6
RGBLIGHT_ENABLE = yes       			# Enable WS2812 RGB underlight
LEADER_ENABLE = no 						# Enable leader key chording
MIDI_ENABLE = no            			# MIDI control
UNICODE_ENABLE = no         			# Unicode
BLUETOOTH = no 							# Bluetooth
SPLIT_KEYBOARD = yes					# Split keyboard
WAIT_FOR_USB = no						# Forces the keyboard to wait for a USB connection to be established before it starts up
NO_USB_STARTUP_CHECK = no				# Disables usb suspend check after keyboard startup
TAP_DANCE_ENABLE = yes					# Enables Tap-Dance functionality
BACKLIGHT_ENABLE = yes      			# Enable keyboard backlight functionality
LINK_TIME_OPTIMIZATION_ENABLE = yes		# Enables Link Time Optimization (LTO) when compiling the keyboard

BOOTLOADER = qmk-dfu					# Defines bootloader
